import { MigrationInterface, QueryRunner, TableColumn } from 'typeorm';

export class RefactorEntityIds1779291915449 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    const tables = ['user', 'tenant', 'tenant_member', 'branch'];

    // Step 1: Add uid column to all tables, populated with old id (uuid)
    for (const table of tables) {
      await queryRunner.addColumn(
        table,
        new TableColumn({
          name: 'uid',
          type: 'uuid',
          isNullable: true,
        }),
      );
      // uid = old uuid id so FK references still match
      await queryRunner.query(`UPDATE "${table}" SET uid = id`);
      await queryRunner.query(
        `ALTER TABLE "${table}" ALTER COLUMN uid SET NOT NULL`,
      );
      await queryRunner.query(
        `ALTER TABLE "${table}" ADD CONSTRAINT "UQ_${table}_uid" UNIQUE (uid)`,
      );
    }

    // Step 2: Add sequences for auto-increment
    for (const table of tables) {
      await queryRunner.query(
        `CREATE SEQUENCE IF NOT EXISTS ${table}_id_seq START 1`,
      );
    }

    // Step 3: Add internal_id column and populate
    for (const table of tables) {
      await queryRunner.addColumn(
        table,
        new TableColumn({
          name: 'internal_id',
          type: 'int',
          isNullable: true,
        }),
      );
      await queryRunner.query(
        `UPDATE "${table}" SET internal_id = nextval('${table}_id_seq')`,
      );
      await queryRunner.query(
        `ALTER TABLE "${table}" ALTER COLUMN internal_id SET NOT NULL`,
      );
    }

    // Step 4: Drop PK constraints with CASCADE to also drop dependent FKs
    for (const table of tables) {
      const pkResult = await queryRunner.query(
        `SELECT conname FROM pg_constraint WHERE conrelid = '"${table}"'::regclass AND contype = 'p'`,
      );
      if (pkResult.length > 0) {
        const pkName = pkResult[0].conname;
        await queryRunner.query(
          `ALTER TABLE "${table}" DROP CONSTRAINT "${pkName}" CASCADE`,
        );
      }
    }

    // Step 5: Drop old id columns and rename internal_id
    for (const table of tables) {
      await queryRunner.query(`ALTER TABLE "${table}" DROP COLUMN "id"`);
      await queryRunner.query(
        `ALTER TABLE "${table}" RENAME COLUMN "internal_id" TO "id"`,
      );
    }

    // Step 6: Add PK and identity to new id columns
    for (const table of tables) {
      await queryRunner.query(`ALTER TABLE "${table}" ADD PRIMARY KEY (id)`);
      await queryRunner.query(
        `ALTER TABLE "${table}" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY`,
      );
    }

    // Step 7: Prepare mapping tables (uid still has old uuid FK values)
    await queryRunner.query(
      `CREATE TEMPORARY TABLE tmp_user_map AS SELECT id, uid FROM "user"`,
    );
    await queryRunner.query(
      `CREATE TEMPORARY TABLE tmp_tenant_map AS SELECT id, uid FROM "tenant"`,
    );

    // Step 8a: tenant.owner_id -> user.id (via uid match - both hold old uuid values)
    await queryRunner.query(`ALTER TABLE "tenant" ADD "owner_id_new" int`);
    await queryRunner.query(
      `UPDATE "tenant" t SET owner_id_new = m.id FROM tmp_user_map m WHERE t.owner_id = m.uid`,
    );
    await queryRunner.query(`ALTER TABLE "tenant" DROP COLUMN "owner_id"`);
    await queryRunner.query(
      `ALTER TABLE "tenant" RENAME COLUMN "owner_id_new" TO "owner_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tenant" ALTER COLUMN "owner_id" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "tenant" ADD CONSTRAINT "fk_tenant_owner_id" FOREIGN KEY (owner_id) REFERENCES "user"(id) ON DELETE RESTRICT`,
    );

    // Step 8b: tenant_member.tenant_id -> tenant.id
    await queryRunner.query(
      `ALTER TABLE "tenant_member" ADD "tenant_id_new" int`,
    );
    await queryRunner.query(
      `UPDATE "tenant_member" tm SET tenant_id_new = m.id FROM tmp_tenant_map m WHERE tm.tenant_id = m.uid`,
    );
    await queryRunner.query(
      `ALTER TABLE "tenant_member" DROP COLUMN "tenant_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tenant_member" RENAME COLUMN "tenant_id_new" TO "tenant_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tenant_member" ALTER COLUMN "tenant_id" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "tenant_member" ADD CONSTRAINT "fk_tenant_member_tenant_id" FOREIGN KEY (tenant_id) REFERENCES "tenant"(id) ON DELETE CASCADE`,
    );

    // Step 8c: tenant_member.user_id -> user.id
    await queryRunner.query(
      `ALTER TABLE "tenant_member" ADD "user_id_new" int`,
    );
    await queryRunner.query(
      `UPDATE "tenant_member" tm SET user_id_new = m.id FROM tmp_user_map m WHERE tm.user_id = m.uid`,
    );
    await queryRunner.query(
      `ALTER TABLE "tenant_member" DROP COLUMN "user_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tenant_member" RENAME COLUMN "user_id_new" TO "user_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "tenant_member" ALTER COLUMN "user_id" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "tenant_member" ADD CONSTRAINT "fk_tenant_member_user_id" FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE`,
    );

    // Step 8d: branch.tenant_id -> tenant.id
    await queryRunner.query(`ALTER TABLE "branch" ADD "tenant_id_new" int`);
    await queryRunner.query(
      `UPDATE "branch" b SET tenant_id_new = m.id FROM tmp_tenant_map m WHERE b.tenant_id = m.uid`,
    );
    await queryRunner.query(`ALTER TABLE "branch" DROP COLUMN "tenant_id"`);
    await queryRunner.query(
      `ALTER TABLE "branch" RENAME COLUMN "tenant_id_new" TO "tenant_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "branch" ALTER COLUMN "tenant_id" SET NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE "branch" ADD CONSTRAINT "fk_branch_tenant_id" FOREIGN KEY (tenant_id) REFERENCES "tenant"(id) ON DELETE CASCADE`,
    );

    // Step 8e: user.active_tenant_id -> tenant.id (nullable)
    await queryRunner.query(
      `ALTER TABLE "user" ADD "active_tenant_id_new" int`,
    );
    await queryRunner.query(
      `UPDATE "user" u SET active_tenant_id_new = m.id FROM tmp_tenant_map m WHERE u.active_tenant_id = m.uid`,
    );
    await queryRunner.query(
      `ALTER TABLE "user" DROP COLUMN "active_tenant_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "user" RENAME COLUMN "active_tenant_id_new" TO "active_tenant_id"`,
    );
    await queryRunner.query(
      `ALTER TABLE "user" ADD CONSTRAINT "fk_user_active_tenant_id" FOREIGN KEY (active_tenant_id) REFERENCES "tenant"(id) ON DELETE SET NULL`,
    );

    // Cleanup
    await queryRunner.query(`DROP TABLE IF EXISTS tmp_user_map`);
    await queryRunner.query(`DROP TABLE IF EXISTS tmp_tenant_map`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const fks = [
      'fk_user_active_tenant_id',
      'fk_branch_tenant_id',
      'fk_tenant_member_user_id',
      'fk_tenant_member_tenant_id',
      'fk_tenant_owner_id',
    ];
    for (const fk of fks) {
      await queryRunner.query(
        `ALTER TABLE "tenant" DROP CONSTRAINT IF EXISTS "${fk}"`,
      );
      await queryRunner.query(
        `ALTER TABLE "tenant_member" DROP CONSTRAINT IF EXISTS "${fk}"`,
      );
      await queryRunner.query(
        `ALTER TABLE "branch" DROP CONSTRAINT IF EXISTS "${fk}"`,
      );
      await queryRunner.query(
        `ALTER TABLE "user" DROP CONSTRAINT IF EXISTS "${fk}"`,
      );
    }
  }
}
