export const ERROR_CODES = {
  BAD_REQUEST: {
    // OTP
    INVALID_OTP: 'INVALID_OTP',
    EXPIRED_OTP: 'EXPIRED_OTP',

    // USER
    USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',

    // Tenant
    TENANT_SUBDOMAIN_EXISTS: 'TENANT_SUBDOMAIN_EXISTS',

    // Validation
    INVALID_TENANT_SUBDOMAIN: 'INVALID_TENANT_SUBDOMAIN',
    INVALID_PHONE_NUMBER: 'INVALID_PHONE_NUMBER',
    INVALID_EMAIL: 'INVALID_EMAIL',
  },
  UNAUTHORIZED: {},
  FORBIDDEN: {},
  NOT_FOUND: {},
  INTERNAL_SERVER_ERROR: {},
  CONFLICT: {},
  TOO_MANY_REQUESTS: {},
  SERVICE_UNAVAILABLE: {},
  GATEWAY_TIMEOUT: {},
};
